### ISSUE TITLE
Not able to preview themes despite API token login being accepted

### ISSUE THREAD

**Issue by mvlad-reb** [zendesk/zcli#250]
## Expectations

Being able to preview the theme being developed successfully locally, or at the very least getting actionable error messages

## Reality

![image](https://github.com/user-attachments/assets/29ae3b24-f558-413e-b558-8450e8a84b02)

## Steps to Reproduce

1. log into zendesk via zcli login -i
2. navigate to theme folder
3. try to preview the theme via yarn start / zcli themes:preview
4. Error 403

### Issue details
This API token and setup has worked before, my account has admin access to the guide section on the user side, and i've already tried removing and re-adding profiles to no avail. The error doesn't really provide more issues if the error is on my side or the zendesk side, but checking the API log on the zendesk side doesn't seem to be logging these attempts.

- Command: zcli themes
- Version: @zendesk/zcli/1.0.0-beta.47 wsl-x64 node-v16.20.2
- OS: Ubuntu 22.04 on WSL2

**Comment by michel-rely** [comment]
Running into the same issue. 

Using: 
`$ DEBUG=* zcli themes:preview`

`
...
Uploading theme... !
Error: Request failed with status code 403
    at error (/usr/lib/node_modules/@zendesk/zcli/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at preview (/usr/lib/node_modules/@zendesk/zcli/node_modules/@zendesk/zcli-themes/dist/lib/preview.js:53:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Preview.run (/usr/lib/node_modules/@zendesk/zcli/node_modules/@zendesk/zcli-themes/dist/commands/themes/preview.js:32:25)
    at async Preview._run (/usr/lib/node_modules/@zendesk/zcli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/lib/node_modules/@zendesk/zcli/node_modules/@oclif/core/lib/config/config.js:301:25)
`

Command: zcli themes
Version: @zendesk/zcli/1.0.0-beta.47 .46 .45
OS: Debian in UTM

**Comment by vagarogit** [comment]
Same issue here. Any word on a fix?

**Comment by mvlad-reb** [comment]
Still getting this issue on 1.0.0 beta 50
![image](https://github.com/user-attachments/assets/f6fca52f-0d03-434e-b0c1-2be0f2b376a8)
This is really frustrating.

**Comment by michel-rely** [comment]
Apparently, you need to set the environment variables too. This fixed my problem after raising this with support. 
https://developer.zendesk.com/documentation/apps/getting-started/using-zcli/#authenticating-zcli-using-environment-variables:~:text=As%20an%20optional%20step%2C%20print%20each%20environment%20variable%27s%20value%20to%20ensure%20it%27s%20set

**Comment by mvlad-reb** [comment]
Unfortunately I already have those set up as well with the same values as the ones I input during the login (I had to, otherwise login was failing):
![image](https://github.com/user-attachments/assets/d737c6d2-71eb-4c66-a54d-c862e87f5587)

still i don't see why they'd be needed any more, since i am successfully logged in and the profile is selected, it should stand to reason that it should just connect using those details there.

**Comment by dinopascale-prima** [comment]
Hello everyone, any updates on this? I cannot make it works and setting up environments doesn't fix the problem. 

@mvlad-reb did you find a solution for this?

**Comment by mvlad-reb** [comment]
If you were using /token before, remove the /token from the email, as API token is the only way to log in. I've added the exports to bashrc, and for the subdomain it doesn't accept custom domains anymore so you need the backend zendesk subdomain, and it seems to work fine for now.
