### ISSUE TITLE
ZCLI update to 1.0.0-beta.15 is causing local development issue

### ISSUE THREAD

**Issue by hr23232323** [zendesk/zcli#99]
## Expectations

Run ZD app locally (using `zcli apps:server`), see working app when navigating to `<subdomain>.zendesk.com/agent/tickets/6?zcli_apps=true`

## Reality

The app is not loading at all. The application was previously working as expected locally (last used on Friday, 12/03), but looks like some PRs/changes were made over the weekend which might've caused this. In specific, are there any changes to the manifest file /configs due to https://github.com/zendesk/zcli/pull/94?

I'm seeing the following error in the browser console-

![image](https://user-images.githubusercontent.com/19507491/144896324-390d811d-cb95-449a-9250-ee29d6625f22.png)

```
[App "R&D Butcherbox App"] Error: Tried to show an iframe with a location that is neither absolute nor an asset: 
    at e.renderTemplate (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:15:38322)
    at n (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:15:39395)
    at e.renderLayout (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:15:39598)
    at l.render (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:1:70925)
    at Zt.componentDidMount (https://static.zdassets.com/agent/assets/react/js/app.a918fc968db70217b.js:9194:3)
    at as (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15150:53)
    at pu (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15400:10)
    at t.unstable_runWithPriority (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15627:12)
    at Vo (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:14791:62)
    at du (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15356:8)
```

## Steps to Reproduce

1. This is in a private app. Our local development manifest.json file can be seen below (**Note: name/email exact values have been replaced with <> for privacy reasons**)-
```
{
  "name": "<>",
  "author": {
    "name": "<>",
    "email": "<>",
    "url": ""
  },
  "defaultLocale": "en",
  "private": true,
  "location": {
    "support": {
      "ticket_sidebar": {
        "url": "http://localhost:8888/sidebar",
        "size": {
          "height": "50px"
        },
        "modal": {
          "url": "https://localhost:8888/modal"
        }
      }
    }
  },
  "version": "1.2.0",
  "frameworkVersion": "2.0"
}
```

### Issue details

- Command: `zcli apps:server`
- Version: 1.0.0-beta.15
- OS: MacOS Big Sur

**Comment by wallter** [comment]
Having a possibly related issue that has started poping up. (Possibly related to https://github.com/zendesk/zcli/pull/94)

Error:
```
vendor-54c5075cd76b323dca94a31cca591995.js:7121 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at s (app_loader.ts?db0a:90)
    at app_loader.ts?db0a:54
    at Array.forEach (<anonymous>)
    at i (app_loader.ts?db0a:50)
    at o (app_loader.ts?db0a:71)
    at index.js?bdd8:49
    at new Promise (<anonymous>)
    at new e (_export.js?ece2:35)
    at d.i [as init] (index.js?bdd8:48)
 ```
 
 Code Debugging:
 ```javascript
 # app_loader.ts
 function reconstructAppLocations(appLocations: Object) {
  const locations = {}
  Object.keys(appLocations).forEach((productName) => { // appLocations is undefined
    locations[productName] = {}
   ...
   
 export function getApps (appsPayload: AppPayload[]) {
  const allApps: Record<string, IframeApp> = {}

  appsPayload.forEach((app) => {
    allApps[app.id] = IframeApp.extend({})
      .reopenClass({
        experiments: app.experiments,
        location: reconstructAppLocations(app.locations), // app.locations === undefined, app.location IS defined
        singleInstall: app.single_install,
        signedUrls: app.signed_urls
      })
```
 
 `appLocations` is provided by `getApps@IframeApp.extend.reopenClass({ location: reconstructAppLocations(app.locations)})` which references `app.locations` — which is undefined while `app.location` (singular) IS defined... mixing `location & locations` in conjunction with changes in https://github.com/zendesk/zcli/pull/94 seem a likely cause.

**Comment by Matenko** [comment]
This was working for us on 12/3 but I'm not able to get a zcli apps:server command to render our app on any version even though there are no console or command line errors specifying an issue. A local ZAT server works fine though.

**Comment by Matenko** [comment]
Some apps having more trouble than other for us. We're getting a similar error as the original issue: 

`vendor-54c5075cd76b323dca94a31cca591995.js:7121 [App "Test App"] Error: Tried to show an iframe with a location that is neither absolute nor an asset: 
    at e.renderTemplate (https://static.zdassets.com/zendesk_app_framework/pod20/framework.min.js:15:38322)
    at n (https://static.zdassets.com/zendesk_app_framework/pod20/framework.min.js:15:39395)
    at e.renderLayout (https://static.zdassets.com/zendesk_app_framework/pod20/framework.min.js:15:39598)
    at l.render (https://static.zdassets.com/zendesk_app_framework/pod20/framework.min.js:1:70925)
    at d.renderWrappedView (https://static.zdassets.com/agent/assets/app_framework-e1885b7e5bca1ef319cb0647a0f6e195.js:325:738)
    at d.v [as _super] (https://static.zdassets.com/agent/assets/vendor-54c5075cd76b323dca94a31cca591995.js:1635:40)
    at d.renderWrappedView (https://static.zdassets.com/agent/assets/app_framework-e1885b7e5bca1ef319cb0647a0f6e195.js:331:432)
    at d.r [as renderWrappedView] (https://static.zdassets.com/agent/assets/vendor-54c5075cd76b323dca94a31cca591995.js:1845:41)
    at didInsertElement (https://static.zdassets.com/agent/assets/app_framework-e1885b7e5bca1ef319cb0647a0f6e195.js:325:620)
    at d.r [as didInsertElement] (https://static.zdassets.com/agent/assets/vendor-54c5075cd76b323dca94a31cca591995.js:1845:41)`

**Comment by wallter** [comment]
Update (12/8) App is working again — thanks for the fix @ZenDesk! 

Steps taken:
- `brew update && brew upgrade`
- `yarn upgrade`
- Updated from OSX Big Sur -> Monterey
- Reset SCM memory

![image](https://user-images.githubusercontent.com/1613806/145278619-7ad65dc0-a418-4ad6-a3c5-e7b5ad74c109.png)

**Comment by hr23232323** [comment]
Alas, the above^ steps don't work for me. I'm still seeing the same error as before-
```
[App "R&D Butcherbox App"] Error: Tried to show an iframe with a location that is neither absolute nor an asset: 
    at e.renderTemplate (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:15:38322)
    at n (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:15:39395)
    at e.renderLayout (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:15:39598)
    at l.render (https://static.zdassets.com/zendesk_app_framework/pod23/framework.min.js:1:70925)
    at Zt.componentDidMount (https://static.zdassets.com/agent/assets/react/js/app.a918fc968db70217b.js:9194:3)
    at as (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15150:53)
    at pu (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15400:10)
    at t.unstable_runWithPriority (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15627:12)
    at Vo (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:14791:62)
    at du (https://static.zdassets.com/agent/assets/react/js/vendor.a85d8c739077c2df3.js:15356:8)
```
@zendesk

**Comment by hr23232323** [comment]
Resolved now. The issue was caused by an interaction between the ZD update and the local project. Solved by deleting the local project and recloning from GH. This refreshed the local folder permissions etc. which were blocking the ZCLI from getting the correct assets to display in the iFrame.

**Comment by cstsz** [comment]
Still seeing this issue after recloning my projects and downgrading to zcli beta.14

**Comment by beletate** [comment]
> Still seeing this issue after recloning my projects and downgrading to zcli beta.14

I'm getting the same issue, even using old versions.

**Comment by tomi-heiskanen** [comment]
For the iframe issue: install zcli beta 14 (also make sure you have node 12+) and then make sure you modify the manifest.json according to this: https://github.com/zendesk/zcli/commit/d40df3e8e9503010068464e0b208c820d97d8c54#diff-52010216df369145c80b3ff4d80040dd25fed42986c34bdd8a3a26bb4426a843L68

Doing the above, fixed the issue for us.
